   LOG VENPRO 2017-05-03
_________________________________________________________
---------------------------------------------------------

2017-05-03 19:7:19 : VENPRO iniciado
2017-05-03 19:7:34 : pru.103. False
2017-05-03 19:7:34 : Error.insert_archivoimport_Mysql(). Error en la sentencia. [codtabla: {2} - nomtabla: {frame}
ValorFILA: [@Tr_Frame=33], [@StartofTicket=1], [@TenderPurchase=0], [@PostVoid=0], [@TicketNumber=1096], [@VoidTicketNumber=0], [@NoSale=0], [@Tail_NumTicketSL=1096], [@Tail_Fecha=2014-12-19], [@Tail_Hora=08:03:31], [@Tail_Devolucion=0], [@Tail_Training=0], [@Tail_Offline=0], [@Tail_TicketCancelado=1], [@Tail_BadRec=0], [@Sequence_ID=41310], [@Tail_NumCajero=6547], [@Tail_NumPOS=11], [@StoreNumber=0103], [@TailSeqHighByte=]
]Archivo:[TRPER20141219A443.XML]
Fecha: [2017-05-03]
tienda: [103]
[INSERT INTO frame ( archivo_venpro,fecha_venpro, fechaprocesamiento_venpro, codtienda_venpro, Tr_Frame, StartofTicket, TenderPurchase, PostVoid, TicketNumber, VoidTicketNumber, NoSale, Tail_NumTicketSL, Tail_Fecha, Tail_Hora, Tail_Devolucion, Tail_Training, Tail_Offline, Tail_TicketCancelado, Tail_BadRec, Sequence_ID, Tail_NumCajero, Tail_NumPOS, StoreNumber, TailSeqHighByte ) 
                                    values ( 'TRPER20141219A443.XML' , '2017-05-03' ,'2017-05-03 19:07:34',103, @Tr_Frame, @StartofTicket, @TenderPurchase, @PostVoid, @TicketNumber, @VoidTicketNumber, @NoSale, @Tail_NumTicketSL, @Tail_Fecha, @Tail_Hora, @Tail_Devolucion, @Tail_Training, @Tail_Offline, @Tail_TicketCancelado, @Tail_BadRec, @Sequence_ID, @Tail_NumCajero, @Tail_NumPOS, @StoreNumber, @TailSeqHighByte )] . Duplicate entry '2014-12-19-41310-11-103' for key 'PRIMARY'
2017-05-03 19:7:34 : Error.insert_archivoimport_Mysql(). Error en la sentencia. [codtabla: {1} - nomtabla: {plu}
ValorFILA: [@Tr_PLU=1], [@CodigoPLU=09999999999994], [@AnularItem=0], [@AnularUltimo=0], [@PriceOverride=0], [@ManualPrice=0], [@Pesable=0], [@Cant_es_Peso=0], [@Linked_Envase=0], [@Escaneado=0], [@BottleDeposit=0], [@BottleRefund=0], [@NumDepartamento=9901], [@Cantidad=1], [@Precio=141219], [@Monto_Recibido=141219], [@TxFlg1=0], [@TxFlg2=0], [@TxFlg3=0], [@TxFlg4=0], [@TxFlg5=0], [@TxFlg6=0], [@TxFlg7=0], [@TxFlg8=0], [@Tail_NumTicketSL=1096], [@Tail_Fecha=2014-12-19], [@Tail_Hora=08:03:32], [@Tail_Devolucion=0], [@Tail_Training=0], [@Tail_Offline=0], [@Tail_TicketCancelado=1], [@Tail_BadRec=0], [@Sequence_ID=41312], [@Tail_NumCajero=6547], [@Tail_NumPOS=11], [@StoreNumber=0103], [@TailSeqHighByte=]
]Archivo:[TRPER20141219A443.XML]
Fecha: [2017-05-03]
tienda: [103]
[INSERT INTO plu ( archivo_venpro,fecha_venpro, fechaprocesamiento_venpro, codtienda_venpro, Tr_PLU, CodigoPLU, AnularItem, AnularUltimo, PriceOverride, ManualPrice, Pesable, Cant_es_Peso, Linked_Envase, Escaneado, BottleDeposit, BottleRefund, NumDepartamento, Cantidad, Precio, Monto_Recibido, TxFlg1, TxFlg2, TxFlg3, TxFlg4, TxFlg5, TxFlg6, TxFlg7, TxFlg8, Tail_NumTicketSL, Tail_Fecha, Tail_Hora, Tail_Devolucion, Tail_Training, Tail_Offline, Tail_TicketCancelado, Tail_BadRec, Sequence_ID, Tail_NumCajero, Tail_NumPOS, StoreNumber, TailSeqHighByte ) 
                                    values ( 'TRPER20141219A443.XML' , '2017-05-03' ,'2017-05-03 19:07:34',103, @Tr_PLU, @CodigoPLU, @AnularItem, @AnularUltimo, @PriceOverride, @ManualPrice, @Pesable, @Cant_es_Peso, @Linked_Envase, @Escaneado, @BottleDeposit, @BottleRefund, @NumDepartamento, @Cantidad, @Precio, @Monto_Recibido, @TxFlg1, @TxFlg2, @TxFlg3, @TxFlg4, @TxFlg5, @TxFlg6, @TxFlg7, @TxFlg8, @Tail_NumTicketSL, @Tail_Fecha, @Tail_Hora, @Tail_Devolucion, @Tail_Training, @Tail_Offline, @Tail_TicketCancelado, @Tail_BadRec, @Sequence_ID, @Tail_NumCajero, @Tail_NumPOS, @StoreNumber, @TailSeqHighByte )] . Duplicate entry '2014-12-19-41312-11-103' for key 'PRIMARY'
2017-05-03 19:7:34 : Error.insert_archivoimport_Mysql(). Error en la sentencia. [codtabla: {36} - nomtabla: {total}
ValorFILA: [@Tr_Total=5], [@MontoTicket=141219], [@NumItems=1], [@Saved_Tkt=0], [@Recalled_Tkt=0], [@GT=753307951], [@Tail_NumTicketSL=1096], [@Tail_Fecha=2014-12-19], [@Tail_Hora=08:03:47], [@Tail_Devolucion=0], [@Tail_Training=0], [@Tail_Offline=0], [@Tail_TicketCancelado=1], [@Tail_BadRec=0], [@Sequence_ID=41320], [@Tail_NumCajero=6547], [@Tail_NumPOS=11], [@StoreNumber=0103], [@TailSeqHighByte=]
]Archivo:[TRPER20141219A443.XML]
Fecha: [2017-05-03]
tienda: [103]
[INSERT INTO total ( archivo_venpro,fecha_venpro, fechaprocesamiento_venpro, codtienda_venpro, Tr_Total, MontoTicket, NumItems, Saved_Tkt, Recalled_Tkt, GT, Tail_NumTicketSL, Tail_Fecha, Tail_Hora, Tail_Devolucion, Tail_Training, Tail_Offline, Tail_TicketCancelado, Tail_BadRec, Sequence_ID, Tail_NumCajero, Tail_NumPOS, StoreNumber, TailSeqHighByte ) 
                                    values ( 'TRPER20141219A443.XML' , '2017-05-03' ,'2017-05-03 19:07:34',103, @Tr_Total, @MontoTicket, @NumItems, @Saved_Tkt, @Recalled_Tkt, @GT, @Tail_NumTicketSL, @Tail_Fecha, @Tail_Hora, @Tail_Devolucion, @Tail_Training, @Tail_Offline, @Tail_TicketCancelado, @Tail_BadRec, @Sequence_ID, @Tail_NumCajero, @Tail_NumPOS, @StoreNumber, @TailSeqHighByte )] . Duplicate entry '2014-12-19-41320-11-103' for key 'PRIMARY'
2017-05-03 19:7:34 : import_archivo().se movió a carpeta OLD el Archivo por PRIMARY.[E:\VENPRO\VENPRO\bin\Debug\import\103\tmp\TRPER20141219A443.XML] 
2017-05-03 19:8:19 : Error GetFileList(). No se pudo listar archivos - ftp://localhost//103/pcmaster/20170503. System.Net.WebException: Error en el servidor remoto: (550) Archivo no disponible (ej. no se encuentra el archivo o no se tiene acceso).
   en System.Net.FtpWebRequest.SyncRequestCallback(Object obj)
   en System.Net.FtpWebRequest.RequestCallback(Object obj)
   en System.Net.CommandStream.Dispose(Boolean disposing)
   en System.IO.Stream.Close()
   en System.IO.Stream.Dispose()
   en System.Net.ConnectionPool.Destroy(PooledStream pooledStream)
   en System.Net.ConnectionPool.PutConnection(PooledStream pooledStream, Object owningObject, Int32 creationTimeout, Boolean canReuse)
   en System.Net.FtpWebRequest.FinishRequestStage(RequestStage stage)
   en System.Net.FtpWebRequest.GetResponse()
   en VENPRO.globales.GetFileList(String rutaserver, String user, String pass) en E:\VENPRO\VENPRO\globales.cs:línea 528
2017-05-03 19:9:19 : Error GetFileList(). No se pudo listar archivos - ftp://localhost//103/pcmaster/20170503. System.Net.WebException: Error en el servidor remoto: (550) Archivo no disponible (ej. no se encuentra el archivo o no se tiene acceso).
   en System.Net.FtpWebRequest.SyncRequestCallback(Object obj)
   en System.Net.FtpWebRequest.RequestCallback(Object obj)
   en System.Net.CommandStream.Dispose(Boolean disposing)
   en System.IO.Stream.Close()
   en System.IO.Stream.Dispose()
   en System.Net.ConnectionPool.Destroy(PooledStream pooledStream)
   en System.Net.ConnectionPool.PutConnection(PooledStream pooledStream, Object owningObject, Int32 creationTimeout, Boolean canReuse)
   en System.Net.FtpWebRequest.FinishRequestStage(RequestStage stage)
   en System.Net.FtpWebRequest.GetResponse()
   en VENPRO.globales.GetFileList(String rutaserver, String user, String pass) en E:\VENPRO\VENPRO\globales.cs:línea 528
2017-05-03 19:9:36 : VENPRO Cerrado.
2017-05-03 19:12:22 : VENPRO iniciado
2017-05-03 19:12:34 : pru.103. False
2017-05-03 19:12:50 : Error btndescargamanual_Click(). System.IndexOutOfRangeException: Índice fuera de los límites de la matriz.
   en VENPRO.Form1.btndescargamanual_Click(Object sender, EventArgs e) en E:\VENPRO\VENPRO\Form1.cs:línea 2765
2017-05-03 19:12:50 : Error GetFileList(). No se pudo listar archivos - ftp://localhost//103/pcmaster/20170503. System.Net.WebException: Error en el servidor remoto: (550) Archivo no disponible (ej. no se encuentra el archivo o no se tiene acceso).
   en System.Net.FtpWebRequest.SyncRequestCallback(Object obj)
   en System.Net.FtpWebRequest.RequestCallback(Object obj)
   en System.Net.CommandStream.Dispose(Boolean disposing)
   en System.IO.Stream.Close()
   en System.IO.Stream.Dispose()
   en System.Net.ConnectionPool.Destroy(PooledStream pooledStream)
   en System.Net.ConnectionPool.PutConnection(PooledStream pooledStream, Object owningObject, Int32 creationTimeout, Boolean canReuse)
   en System.Net.FtpWebRequest.FinishRequestStage(RequestStage stage)
   en System.Net.FtpWebRequest.GetResponse()
   en VENPRO.globales.GetFileList(String rutaserver, String user, String pass) en E:\VENPRO\VENPRO\globales.cs:línea 528
2017-05-03 19:13:22 : Error GetFileList(). No se pudo listar archivos - ftp://localhost//103/pcmaster/20170503. System.Net.WebException: Error en el servidor remoto: (550) Archivo no disponible (ej. no se encuentra el archivo o no se tiene acceso).
   en System.Net.FtpWebRequest.SyncRequestCallback(Object obj)
   en System.Net.FtpWebRequest.RequestCallback(Object obj)
   en System.Net.CommandStream.Dispose(Boolean disposing)
   en System.IO.Stream.Close()
   en System.IO.Stream.Dispose()
   en System.Net.ConnectionPool.Destroy(PooledStream pooledStream)
   en System.Net.ConnectionPool.PutConnection(PooledStream pooledStream, Object owningObject, Int32 creationTimeout, Boolean canReuse)
   en System.Net.FtpWebRequest.FinishRequestStage(RequestStage stage)
   en System.Net.FtpWebRequest.GetResponse()
   en VENPRO.globales.GetFileList(String rutaserver, String user, String pass) en E:\VENPRO\VENPRO\globales.cs:línea 528
2017-05-03 19:13:36 : VENPRO Cerrado.
